import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import { Provider } from './providers';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-slate-200 h-screen">
        <Provider>
          <div className="flex w-full min-h-screen">
            <div className="flex flex-col w-full">
              <div className="w-full fixed top-0 z-10">
                <Navbar />
              </div>
              <div className="flex relative top-14">{children}</div>
              <Toaster />
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
